config/routes.rb
Rails.application.routes.draw do


  #resources :phases

  root "home#home1"
  get "phases/phase1"
  get "phases/phase2"
  get "phases/phase3"
  get 'home/about'
  get 'home/contact'
  get 'pstaffs/showuser'
  get 'home/index'


  get 'user_profiles/temporary_staff'
  get 'user_profiles/scholars'
  get 'user_profiles/others'

  get "check/phase1/pstaff/:id", :action=>"show_form",:controller =>"check", :as =>"show_user_form"
  patch "/generate/sticker/:id", :action=>"sticker",:controller =>"check",:as =>"sticker_number"
  patch "/generate/remark/:id", :action=>"remark",:controller=>"check", :as =>"remark"



  resources :pstaffs
  resources :user_profiles

  devise_scope :user do
  	delete 'sign_out', to: 'devise/sessions#new'
  end

  devise_for :users, controllers: { registrations: "registrations" }


  resources :users


  get "check/phase1"
  get "check/phase2"
  get "check/phase3"
  #get "check/sticker"
  get  "check/show_user_form/:id" , :action=>"show_user_form", :controller=>"check", :as=>"show_user"
  post "request/approve/:id" , :action=>"approve",:controller=>"check",:as=>"approve"  
  post "request/disapprove/:id" , :action=>"disapprove",:controller=>"check",:as=>"disapprove"  

  post'request/check/:id' => 'check#create', :action=> "create", :controller=>"check" ,:as => 'check'


  get :approve_mail, to: 'notification#approve_mail', as: :approve_mail
  get :recive_mail, to: 'notify#recive_mail', as: :recive_mail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/check_controller.rb
class CheckController < ApplicationController
  skip_before_action :verify_authenticity_token,:only =>[:sticker,:remark]
  before_action :authenticate_user!,expect: [:show,:index]
	def phase1
        if current_user.phase1 == true
            @phases= Pstaff.where("disapprove = false AND phase1 = false", params[:pstaffs], false)
        else
            redirect_to new_user_session_path
        end

  end

  def phase2
    if current_user.phase2 == true
      @phases= Pstaff.where("disapprove = false AND phase1 = true AND phase2 = false", params[:pstaffs], false)
    else
      redirect_to new_user_session_path
    end
  end

    def phase3
        if current_user.phase3 == true
          @phases= Pstaff.where("disapprove = false AND phase2 = true AND phase3 = false", params[:pstaffs], false)
          @phases1= Pstaff.where("disapprove = false AND phase2 = true AND phase3 = true", params[:pstaffs], false)
        else
            redirect_to new_user_session_path
        end
    end

    def admin
      @phases= Pstaff.all
    end

    def remark
        @current_user = current_user
        @remark=Pstaff.find(params[:id])
        if params[:commit]=='Submit'
            if current_user.phase1 == true
                x=Pstaff.find(@remark.id)
                x.phase1=true
                x.phase1_remark=pstaff_params[:phase1_remark]


                @user = User.all
                for i in @user do
                  if(i.role == x.department)
                    @id = i
                    break
                  end
                end
                x.save

                NotifyMailer.with(user: @id).recive_email.deliver


                #@p = User.find(z)
                # NotificationMailer.with(user:@p).approve_email.deliver
                flash[:notice] = "approved succesfully!"
                redirect_to check_phase1_path
            elsif current_user.phase2 == true
                user=Pstaff.find(@remark.id)
                user.phase2_remark=pstaff_params[:phase2_remark]
                user.phase2=true
                @user = User.all
                for i in @user do
                  if(i.phase3 == true)
                    @id = i
                    break
                  end
                end
                user.save
                NotifyMailer.with(user: @id).recive_email.deliver

                flash[:notice] = "approved succesfully!"
                redirect_to check_phase2_path

            elsif current_user.phase3 == true
                @user=Pstaff.find(@remark.id)
                @user.phase3=true
                @user.sticker=pstaff_params[:sticker]
                @user.save
                #NotificationMailer.with(user:@p).disapprove_email.deliver
                flash[:notice] = "approved succesfully!"
                redirect_to check_phase3_path()
            else
        end
   
            
        end
    end



   def show_user_form
       @pstaff=Pstaff.find(params[:id])
       @user_profile = UserProfile.find(@pstaff.user_profile_id)
        #redirect_to pstaff_path(@pstaff)
   end
    
    def approve
    if current_user.phase1 == true
    
    	x=Pstaff.find(params[:id])
        x.phase1=true
        x.save
        # NotificationMailer.with(user:@p).approve_email.deliver
         flash[:notice] = "approved succesfully!"
         redirect_to check_phase1_path
    
    elsif current_user.phase2 == true
    	user=Pstaff.find(params[:id])
        user.phase2=true
        user.save
        flash[:notice] = "approved succesfully!"
        redirect_to check_phase2_path
    
    elsif current_user.phase3 == true
    
    	@user=Pstaff.find(params[:id])
        @user.phase3=true
        @user.save
        flash[:notice] = "approved succesfully!"
        redirect_to check_phase3_path()
    else
    end
    end

    def disapprove

        if current_user.phase1 == true
        
        x=Pstaff.find(params[:id])
        x.disapprove= true
        x.save
        # z = x.user_id
        # x.save
        # @p = User.find(z)
        #  NotificationMailer.with(user:@p).disapprove_email.deliver
        flash[:notice] = "application disapprove succesfully"

        redirect_to check_phase1_path
    elsif current_user.phase2 == true
        user=Pstaff.find(params[:id])
        user.disapprove = true
        user.save
        # z = user.user_id
        # user.save
        # @p = User.find(z)
        #  NotificationMailer.with(user:@p).disapprove_email.deliver
        flash[:notice] = "application disapprove succesfully"

        redirect_to check_phase2_path
    elsif current_user.phase3 == true

        @user=Pstaff.find(params[:id])

        @user.disapprove =true
        @user.save
        flash[:notice] = "application disapprove succesfully"
        redirect_to check_phase3_path
    else
    end
        
    end
    

    def pstaff_params
        params.require(:pstaff).permit(:sticker,:vichel_no,:phase1_remark,:phase2_remark,:phase3_remark)
    end


  # def sticker
  #      @sticker=Pstaff.find(params[:id])
  #      if params[:commit]=='Submit'
  #
  #      if current_user.phase3 == true
  #        @user=Pstaff.find(@sticker.id)
  #        @user.phase3=true
  #        @user.sticker=pstaff_params[:sticker]
  #        @user.save
  #      end
  #      end
  # end

end

app/helpers/check_helper.rb
module CheckHelper
end

app/views/check/_remark_modal.html.erb
  <%=form_for([@current_user,@remark],:url=>remark_path) do |f| %>


    <%= f.text_field :vichel_no,{:class=>'form-control',:placeholder=>'Sticker Number',:required=>true,:readonly=>true} %>
    <br>
    <% if @current_user.phase1 == true %>
    <%= f.text_field :phase1_remark,{:class=>'form-control',:placeholder=>'Remark',:required=>true} 
    %>
    <br>

    <%=f.button "approve",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>
    <% elsif @current_user.phase2 == true %>
         <%= f.text_field :phase2_remark,{:class=>'form-control',:placeholder=>'Remark',:required=>true} %>
         <br>

    <%=f.button "approve",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>
    <% elsif @current_user.phase3 == true %>
        <%= f.text_field :sticker,{:class=>'form-control',:placeholder=>'Sticker Number',:required=>true} %>
        <br>

    <%=f.button "disapprove",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>
    	
    <%end%>
  <% end %>

app/views/check/_sticker_modal.html.erb
<%=form_for(@sticker,:url=>sticker_number_path) do |f| %>


    <%= f.text_field :vichel_no,{:class=>'form-control',:placeholder=>'Sticker Number',:required=>true,:readonly=>true} %>
    <br>
    <%= f.text_field :sticker,{:class=>'form-control',:placeholder=>'Sticker Number',:required=>true} %>
    <br>
    <%=f.button "approve",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>



  <% end %>

<%=form_for([@current_user,@remark],:url=>remark_path) do |f| %>


  <%= f.text_field :vichel_no,{:class=>'form-control',:placeholder=>'Sticker Number',:required=>true,:readonly=>true} %>
  <br>
  <% if @current_user.phase1 == true %>
    <%= f.text_field :phase1_remark,{:class=>'form-control',:placeholder=>'Remark',:required=>true}
    %>
    <br>

    <%=f.button "approve",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>
  <% elsif @current_user.phase2 == true %>
    <%= f.text_field :phase2_remark,{:class=>'form-control',:placeholder=>'Remark',:required=>true} %>
    <br>

    <%=f.button "approve",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>
  <% elsif @current_user.phase3 == true %>
    <%= f.text_field :phase3_remark,{:class=>'form-control',:placeholder=>'Remark',:required=>true} %>
    <br>

    <%=f.button "disapprove",:name=>"commit",:value=>"Submit",:class=>'btn btn-sm btn-success',:remote=>true %>

  <%end%>
<% end %>

app/views/check/new.html.erb
<%= form_tag({controller: "check", action: "new"}, method: "post") do %>
    <%= label_tag(:sticker, "Sticker Number:") %>
    <%= text_field_tag(:sticker) %>
    <%= hidden_field_tag(:@user, params["@user"])%>
    <%= submit_tag("submit") %>
<% end %>

app/views/check/phase1.html.erb
<% if current_user.phase1 ==true%>
<h2 class="text-center"><b>Unapproved Application</b></h2>
<table id="table_id" class="table table-striped  table-hover table-bordered">
          <thead >
          <tr>
      <th>Name</th>
      <th>EMP_ID</th>
      <th>Department</th>
      <th>Applicant Type</th>
      <th>show</th>
      <th>Approve</th>
      <th>Disapprove</th>
      </tr>
  </thead>
<tbody >
<% @phases.each do |phase| %>
<% @phase =phase %>
<% @user_profile = UserProfile.find(phase.user_profile_id)%>
   <tr>
       <td ><%= @user_profile.name %></td>
        <td ><%= @user_profile.unique_id %></td>
       <td ><%= @user_profile.department %></td>
       <td><%= @user_profile.applicant_type%></td>
       <td ><%= link_to "Show", show_user_path(@phase.id), method: :get,class:"btn btn-primary btn-sm" %></td>
<!--       <td><button type="button" class="btn btn-warning btn-md" data-toggle="modal" style="margin:10px;"  onclick="sticker_allotment(<%#= @phase.id%>);" data-disable-with="Validating ...">Approve</button></td>-->
     <td ><%= link_to "Approve", approve_path(@phase.id), method: :post,class:"btn btn-primary btn-sm" %></td>
         <td ><%= link_to "Disapprove", disapprove_path(@phase), method: :post,class:"btn btn-primary btn-sm" %></td>
         
         
       
   </tr>
  <%end %>

</tbody>
</table>

 
<% else %>
    <%= render "devise/sessions#new" %>
<%end %>


 <!--  for remark -->

<div class="modal fade" id="myModal1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content"><div class="modal-body" id="modal_response1">
    </div>
    </div>
  </div>
</div>
<script>
    function sticker_allotment(id){
        $.ajax({
            type: "PATCH",
            url: "/generate/remark/"+id,
            dataType: "script",
            success: function(data) {
                console.log(data);
            }
        });
    }
</script>
<script >$(document).ready( function () {
    $('#table_id').DataTable();
} )</script>

app/views/check/phase2.html.erb
<% if current_user.phase2 ==true%>
<h2 class="text-center"><b>Unapproved Application</b></h2>
<table id="table_id" class="table table-striped  table-hover table-bordered">
  <thead style="font-size: large">
  <tr >
      <th>Name</th>
      <th>EMP_ID</th>
      <th>Department</th>
      <th>Applicant Type</th>
      <th>show</th>
      <th>Aprrove</th>
      <th>Disapprove</th>
      
    </tr>
 </thead>

<tbody>
<% @phases.each do |phase| %>
  <% @phase =phase %>
  <% @user_profile = UserProfile.find(phase.user_profile_id)%>
        <%# if @user_profile.department == current_user.role %>
           <tr>
         <td ><%= @user_profile.name %></td>
         <td ><%= @user_profile.unique_id %></td>
         <td ><%= @user_profile.department %></td>
         <td><%=  @user_profile.applicant_type%></td>
         <td ><%= link_to "Show", show_user_path(phase.id), method: :get,class:"btn btn-primary btn-sm" %></td>
         <!-- <td ><%= link_to "Approve", approve_path(phase), method: :post,class:"btn btn-primary btn-sm" %></td> -->
<!--         <td><button type="button" class="btn btn-warning btn-md" data-toggle="modal" style="margin:10px;"  onclick="sticker_allotment(<%#= phase.id%>);" data-disable-with="Validating ...">Approve</button></td>-->
             <td ><%= link_to "Approve", approve_path(phase), method: :post,class:"btn btn-primary btn-sm" %></td>

             <td ><%= link_to "Disapprove", disapprove_path(phase), method: :post,class:"btn btn-primary btn-sm" %></td>
   

       
       </tr>
    <%# end %>
  <%end %>

</tbody>
</table>
<% else %>
   <%= render "devise/sessions#new" %>
<% end %>
 </div>
 </div>
 </div>

<!--  for remark -->

<div class="modal fade" id="myModal1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content"><div class="modal-body" id="modal_response1">
    </div>
    </div>
  </div>
</div>

<script>
    function sticker_allotment(id){
        $.ajax({
            type: "PATCH",
            url: "/generate/remark/"+id,
            dataType: "script",
            success: function(data) {
                console.log(data);
            }
        });
    }
</script>

<script >$(document).ready( function () {
    $('#table_id').DataTable();
} )</script>

app/views/check/phase3.html.erb
<% if current_user.phase3 ==true%>

<h2 class="text-center"><b>Unapproved Application</b></h2>


<table id="table_id" class="table table-striped">
<thead>
            <tr>
            <th>Name</th>
            <th>EMP_ID</th>
            <th>Department</th>
            <th>Applicant Type</th>
            <th>Show</th>
            <th>approve</th>
          </tr>
</thead>
<tbody>
<% @phases.each do |phase| %>
  <% @phase =phase %>
  <% @user_profile = UserProfile.find(phase.user_profile_id)%>
  <tr>

       <td ><%= @user_profile.name %></td>
       <td ><%=@user_profile.unique_id %></td>
       <td ><%= @user_profile.department %></td>
       <td><%= @user_profile.applicant_type%></td>
       <td ><%= link_to "Show", show_user_path(phase.id), method: :get,class:"btn btn-primary btn-sm" %></td>
      <td><button type="button" class="btn btn-warning btn-md" data-toggle="modal" style="margin:10px;"  onclick="remark(<%= phase.id%>);" data-disable-with="Validating ...">Disapprove</button></td>
   
  </tr>
    <% end %>
</tbody>
</table>

<h2 class="text-center"><b>Unapproved Application</b></h2>

<table id="table_id1" class="table table-striped">
<thead>
            <tr>
            <th>Name</th>
            <th>EMP_ID</th>
            <th>Department</th>
            <th>Applicant Type</th>
            <th>Show</th>
            <th>Sticker Number</th>
          </tr>
</thead>
<tbody>
<% @phases1.each do |phase| %>
  <% @phase =phase %>
  <% @user_profile = UserProfile.find(phase.user_profile_id)%>
<tr>

       <td ><%= @user_profile.name %></td>
       <td ><%= @user_profile.unique_id %></td>
       <td ><%= @user_profile.department %></td>
       <td><%= @user_profile.applicant_type%></td>
       <td ><%= link_to "Show", show_user_path(phase.id), method: :get,class:"btn btn-primary btn-sm" %></td>
        <td><%=phase.sticker%></td>
  </tr>
    <% end %>

</tbody>
</table>
<% else %>
   <%= render "devise/sessions#new" %>
<% end %>
 



<!-- for sticker model -->

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content"><div class="modal-body" id="modal_response">
    </div>
    </div>
  </div>
</div>

<!--  for remark -->

<div class="modal fade" id="myModal1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content"><div class="modal-body" id="modal_response1">
    </div>
    </div>
  </div>
</div>

<script>
    function sticker_allotment(id){
        $.ajax({
            type: "PATCH",
            url: "/generate/sticker/"+id,
            dataType: "script",
            success: function(data) {
                console.log(data);
            }
        });
    }
    function remark(id){
        $.ajax({
            type: "PATCH",
            url: "/generate/remark/"+id,
            dataType: "script",
            success: function(data) {
                console.log(data);
            }
        });
    }
</script>

<script >$(document).ready( function () {
    $('#table_id').DataTable();
} )</script>
<script >$(document).ready( function () {
    $('#table_id1').DataTable();
} )</script>

 

app/views/check/remark.js.erb
$('#modal_response1').html('<%= escape_javascript(render :partial => 'remark_modal') %>');
$('#myModal1').modal('show');

app/views/check/show_user_form.html.erb
<div class="container" >
<table class="table table-striped" >
  <thead>
  <tr>
    <th scope="col"style="font-size: large">Serial no.</th>
    <th scope="col" style="font-size: large">Field</th>
    <th scope="col" style="font-size: large">infromation</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <th scope="row">1</th>
    <td style="font-size: large">User Id</td>
    <td style="font-size: large"><%=@pstaff.id%></td>

  </tr>
  <tr>
    <th scope="row">2</th>
    <td style="font-size: large">Name</td>
    <td style="font-size: large"><%=@user_profile.name%></td>

  </tr>
  <tr>
    <th scope="row">3</th>
    <td style="font-size: large">Unique Id</td>
    <td style="font-size: large"><%=@user_profile.unique_id%></td>
  </tr>


  <tr>
    <th  scope="row">4</th>
    <td style="font-size: large">Gender</td>
    <td style="font-size: large"><%=@user_profile.gender%></td>
  </tr>

  <tr>
    <th scope="row">5</th>
    <td style="font-size: large">Mobile no.</td>
    <td style="font-size: large"><%=@user_profile.mobile_no%></td>
  </tr>

  <tr>
    <th scope="row">6</th>
    <td style="font-size: large">Department</td>
    <td style="font-size: large"><%=@user_profile.department%></td>
  </tr>


  <tr>
    <th scope="row">7</th>
    <td style="font-size: large">Vehicle No.</td>
    <td style="font-size: large"><%=@pstaff.vichel_no%></td>
  </tr>


  <tr>
    <th scope="row">8</th>
    <td style="font-size: large">Vehicle Type</td>
    <td style="font-size: large"><%=@pstaff.vehical_type%></td>
  </tr>


  <tr>
    <th scope="row">9</th>
    <td style="font-size: large">Vehicle Model</td>
    <td style="font-size: large"><%=@pstaff.vichel_model%></td>
  </tr>


  <tr>
    <th scope="row">10</th>
    <td style="font-size: large">Address</td>
    <td style="font-size: large"><%=@user_profile.address%></td>
  </tr>

  <tr>
    <th scope="row">11</th>
    <td style="font-size: large">Registration Certificate</td>
    <td style="font-size: large">
        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">view</button>
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog modal-lg modal-full">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body ">
                          <iframe src="<%= @pstaff.registration_certificate %>" width="100%" height="500px">
                            <p>Your browser does not support iframes.</p>
                          </iframe>
              </div>

            </div>

          </div>
        </div>


    </td>
  </tr>


  <tr>
    <th scope="row">12</th>
    <td style="font-size: large">ID_PROOF</td>
    <td style="font-size: large">
      <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal1">view</button>
      <!-- Modal -->
      <div class="modal fade" id="myModal1" role="dialog">
        <div class="modal-dialog modal-lg modal-full">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body ">
              <iframe src="<%=@user_profile.id_proof%>" width="100%" height="500px">
                <p>Your browser does not support iframes.</p>
              </iframe>
            </div> 

          </div>

        </div>
      </div>



    </td>
  </tr>

  <% if @user_profile.applicant_type == 'Student'%>
  <tr>
    <th scope="row">12</th>
    <td style="font-size: large">Medical Certificate  </td>
    <td style="font-size: large">
      <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal1">view</button>
      <!-- Modal -->
      <div class="modal fade" id="myModal1" role="dialog">
        <div class="modal-dialog modal-lg modal-full">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body ">
              <iframe src="<%=@pstaff.document%>" width="100%" height="500px">
                <p>Your browser does not support iframes.</p>
              </iframe>
            </div> 

          </div>

        </div>
      </div>



    </td>
  </tr>
  <%end%>
  <tr>
    <th scope="row">13</th>
    <td style="font-size: large">RC holder name</td>
    <td style="font-size: large"><%=@pstaff.RC_holder_name%></td>
  </tr>

  <tr>
    <th scope="row">14</th>
    <td style="font-size: large">Relationship</td>
    <td style="font-size: large"><%=@pstaff.relationship%></td>
  </tr>
  </tbody>
</table>



<%= link_to 'back', :back,class:"btn btn-primary"  %>
</div>

app/views/check/sticker.js.erb
$('#modal_response').html('<%= escape_javascript(render :partial => 'sticker_modal') %>');
$('#myModal').modal('show');