config/routes.rb
Rails.application.routes.draw do


  #resources :phases

  root "home#home1"
  get "phases/phase1"
  get "phases/phase2"
  get "phases/phase3"
  get 'home/about'
  get 'home/contact'
  get 'pstaffs/showuser'
  get 'home/index'


  get 'user_profiles/temporary_staff'
  get 'user_profiles/scholars'
  get 'user_profiles/others'

  get "check/phase1/pstaff/:id", :action=>"show_form",:controller =>"check", :as =>"show_user_form"
  patch "/generate/sticker/:id", :action=>"sticker",:controller =>"check",:as =>"sticker_number"
  patch "/generate/remark/:id", :action=>"remark",:controller=>"check", :as =>"remark"



  resources :pstaffs
  resources :user_profiles

  devise_scope :user do
  	delete 'sign_out', to: 'devise/sessions#new'
  end

  devise_for :users, controllers: { registrations: "registrations" }


  resources :users


  get "check/phase1"
  get "check/phase2"
  get "check/phase3"
  #get "check/sticker"
  get  "check/show_user_form/:id" , :action=>"show_user_form", :controller=>"check", :as=>"show_user"
  post "request/approve/:id" , :action=>"approve",:controller=>"check",:as=>"approve"  
  post "request/disapprove/:id" , :action=>"disapprove",:controller=>"check",:as=>"disapprove"  

  post'request/check/:id' => 'check#create', :action=> "create", :controller=>"check" ,:as => 'check'


  get :approve_mail, to: 'notification#approve_mail', as: :approve_mail
  get :recive_mail, to: 'notify#recive_mail', as: :recive_mail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    if current_user.phase1 == true
           redirect_to check_phase1_path

    elsif current_user.phase2 == true
        redirect_to check_phase2_path



    elsif current_user.phase3 == true
         redirect_to check_phase3_path

      
    else
      @user_profile = current_user.user_profiles
      if @user_profile.ids.count == 0

      else
        redirect_to user_profiles_path
      end
    end
	end


	def about
    end


   def contact
   end

   def home1
   	
   end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1> about us </h1>

app/views/home/contact.html.erb
<h1> contact us </h1>

app/views/home/index.html.erb
<section id="team" class="pb-5">
  <div class="container">
    <h5 class="section-title h1">Apply As</h5>
    <div class="row">
      <!-- Team member -->
      <div class="col-xs-12 col-sm-6 col-md-4">
<!--        <div class="image-flip" ontouchstart="this.classList.toggle('hover');">-->
<!--          <div class="mainflip">-->
            <div class="frontside">
              <div class="card">
                <div class="card-body text-center">
                  <p><img class=" img-fluid" src="https://sunlimetech.com/portfolio/boot4menu/assets/imgs/team/img_01.png" alt="card image"></p>
                  <h2 class="card-title">Permanant Staff</h2>
                  <button type="submit" class="btn navbar-btn btn-danger" name="logout" ><%= link_to "apply",new_user_profile_path %> </button>

                </div>
              </div>
            </div>


      </div>

      <div class="col-xs-12 col-sm-6 col-md-4">
        <!--        <div class="image-flip" ontouchstart="this.classList.toggle('hover');">-->
        <!--          <div class="mainflip">-->
        <div class="frontside">
          <div class="card">
            <div class="card-body text-center">
              <p><img class=" img-fluid" src="https://sunlimetech.com/portfolio/boot4menu/assets/imgs/team/img_01.png" alt="card image"></p>
              <h2 class="card-title">Temparary Staff</h2>
              <button type="submit" class="btn navbar-btn btn-danger" name="logout" ><%= link_to "apply",user_profiles_temporary_staff_path %></button>

            </div>
          </div>
        </div>



      </div>

      <div class="col-xs-12 col-sm-6 col-md-4">
        <!--        <div class="image-flip" ontouchstart="this.classList.toggle('hover');">-->
        <!--          <div class="mainflip">-->
        <div class="frontside">
          <div class="card">
            <div class="card-body text-center">
              <p><img class=" img-fluid" src="https://sunlimetech.com/portfolio/boot4menu/assets/imgs/team/img_01.png" alt="card image"></p>
              <h2 class="card-title">Scholars</h2>
              <button type="submit" class="btn navbar-btn btn-danger" name="logout" ><%= link_to "apply", user_profiles_scholars_path%> </button>

            </div>
          </div>
        </div>



      </div>

      <div class="col-xs-12 col-sm-6 col-md-4">
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <!--        <div class="image-flip" ontouchstart="this.classList.toggle('hover');">-->
        <!--          <div class="mainflip">-->
        <div class="frontside">
          <div class="card">
            <div class="card-body text-center">
              <p><img class=" img-fluid" src="https://sunlimetech.com/portfolio/boot4menu/assets/imgs/team/img_01.png" alt="card image"></p>
              <h2 class="card-title">Others</h2>
              <button type="submit" class="btn navbar-btn btn-danger" name="logout" > <%= link_to "apply",user_profiles_others_path %></button>

            </div>
          </div>
        </div>



      </div>
      </div>



    </div>
  </div>

</section>