config/routes.rb
Rails.application.routes.draw do


  #resources :phases

  root "home#home1"
  get "phases/phase1"
  get "phases/phase2"
  get "phases/phase3"
  get 'home/about'
  get 'home/contact'
  get 'pstaffs/showuser'
  get 'home/index'


  get 'user_profiles/temporary_staff'
  get 'user_profiles/scholars'
  get 'user_profiles/others'

  get "check/phase1/pstaff/:id", :action=>"show_form",:controller =>"check", :as =>"show_user_form"
  patch "/generate/sticker/:id", :action=>"sticker",:controller =>"check",:as =>"sticker_number"
  patch "/generate/remark/:id", :action=>"remark",:controller=>"check", :as =>"remark"



  resources :pstaffs
  resources :user_profiles

  devise_scope :user do
  	delete 'sign_out', to: 'devise/sessions#new'
  end

  devise_for :users, controllers: { registrations: "registrations" }


  resources :users


  get "check/phase1"
  get "check/phase2"
  get "check/phase3"
  #get "check/sticker"
  get  "check/show_user_form/:id" , :action=>"show_user_form", :controller=>"check", :as=>"show_user"
  post "request/approve/:id" , :action=>"approve",:controller=>"check",:as=>"approve"  
  post "request/disapprove/:id" , :action=>"disapprove",:controller=>"check",:as=>"disapprove"  

  post'request/check/:id' => 'check#create', :action=> "create", :controller=>"check" ,:as => 'check'


  get :approve_mail, to: 'notification#approve_mail', as: :approve_mail
  get :recive_mail, to: 'notify#recive_mail', as: :recive_mail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_many   :pstaffs
  has_attached_file :photo
  validates_attachment :photo, :content_type=>{ :content_type => %w(application/pdf image/jpg image/jpeg image/png application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  has_attached_file :id_proof
  validates_attachment :id_proof,:content_type=>{ :content_type => %w(application/pdf image/jpg image/jpeg image/png application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  GENDER = ['Male','Female','Others']

  TEMP = ['MACS', 'Computer Science', 'Mechanical','Civil','Electronic','Mining','Library','Academic','Account','Hostel','CCC','Audit','Administrator']
  TEMP1 = ['MACS', 'Computer Science', 'Mechanical','Civil','Electronic','Mining']
  TEMP2 = ['HCC', 'Guest House', 'Sports','Post Office','Placement','Garden','Compretive Society']

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,expect: [:index]
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    redirect_to pstaffs_path
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
      @x  = @user_profile.user_id
       redirect_to pstaff_path(@x)
  end

  # GET /user_profiles/new
  def new
    # @user_profile = UserProfile.new
    if(current_user.phase1 == false &&  current_user.phase2 == false && current_user.phase3 == false)

      @user_profile = current_user.user_profiles.build
    else
       redirect_to new_user_session_path
    end
  end

  def temporary_staff

    if(current_user.phase1 == false &&  current_user.phase2 == false && current_user.phase3 == false)

      @user_profile = current_user.user_profiles.build
    else
      redirect_to new_user_session_path
    end

  end

  def scholars
    if(current_user.phase1 == false &&  current_user.phase2 == false && current_user.phase3 == false)

      @user_profile = current_user.user_profiles.build
    else
      redirect_to new_user_session_path
    end
  end

  def others
    if(current_user.phase1 == false &&  current_user.phase2 == false && current_user.phase3 == false)
      @user_profile = current_user.user_profiles.build
    else
      redirect_to new_user_session_path
    end
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = current_user.user_profiles.build(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to pstaffs_path, notice: 'User profile was successfully created.' }
        #format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:name, :unique_id, :gender, :mobile_no, :department, :applicant_type, :address,:id_proof,:photo)
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= bootstrap_form_with(model: user_profile, local: true) do |form| %>
  <%if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container_fluid">
      <div class="row" >
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="shadow-lg p-3 mb-5 bg-black rounded">
            <div class="card ">
              <div class="card-header bg-info text-white text-center"><h2>Permanent Staff</h2></div>
              <div class="card-body"> <div class="field" >
  <div class="field">
   
    <h5><%= form.text_field :name,:required=>true, class:"label" %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :unique_id , label: "Employee ID",:required=>true , class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :gender, Pstaff::GENDER %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :mobile_no,label:"Mobile No",:required=>true, class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :department, Pstaff::TEMP ,:required=>true , class:"label" %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :applicant_type %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :address, :required=>true,class:"label"%></h5>
  </div>
  <!-- <div class="file">
    <h5><%= form.file_field :photo ,:required=>true , class:"label,ui pink button"%></h5>
  </div>
 

  <div class="file">
    <h5><%= form.file_field :id_proof ,:required=>true , class:"label,ui pink button"%></h5>
  </div> -->

  <input type="file" name="filePhoto" value="" id="filePhoto"     
  class="required borrowerImageFile" data-errormsg="PhotoUploadErrorMsg">
  <img id="previewHolder" alt="Uploaded Image Preview Holder" width="250px" height="250px"/>


  <div class="actions">
    <h5><%= form.submit "submit",class:"btn btn-primary" %></h5>
  </div>

</div>
</div>
</div>
</div>

<% end %>
<script type="text/javascript">

function readURL(input) {
if (input.files && input.files[0]) {
var reader = new FileReader();
reader.onload = function(e) {
  $('#previewHolder').attr('src', e.target.result);
}

reader.readAsDataURL(input.files[0]);
}
}

$("#filePhoto").change(function() {
readURL(this);
});

</script>

app/views/user_profiles/_others_form.html.erb
<%= bootstrap_form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
        <% user_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container_fluid">
      <div class="row" >
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="shadow-lg p-3 mb-5 bg-black rounded">
            <div class="card ">
              <div class="card-header bg-info text-white text-center"><h2>Other members</h2></div>
              <div class="card-body"> <div class="field" >
  <div class="field">
   
    <h5><%= form.text_field :name,:required=>true, class:"label" %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :unique_id , label: "Employee ID",:required=>true , class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :gender, Pstaff::GENDER %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :mobile_no,label:"Mobile No",:required=>true, class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :department, Pstaff::TEMP2 ,:required=>true , class:"label" %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :applicant_type %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :address, :required=>true,class:"label"%></h5>
  </div>
  <div class="file">
    <h5><%= form.file_field :photo ,:required=>true , class:"label,ui pink button"%></h5>
  </div>
 

  <div class="file">
    <h5><%= form.file_field :id_proof ,:required=>true , class:"label,ui pink button"%></h5>
  </div>


  <div class="actions">
    <h5><%= form.submit "submit",class:"btn btn-primary" %></h5>
  </div>

</div>
</div>
</div>
</div>
<% end %>

app/views/user_profiles/_scholars_form.html.erb
<%= bootstrap_form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
        <% user_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container_fluid">
      <div class="row" >
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="shadow-lg p-3 mb-5 bg-black rounded">
            <div class="card ">
              <div class="card-header bg-info text-white text-center"><h2>Permanent Staff</h2></div>
              <div class="card-body"> <div class="field" >
  <div class="field">
   
    <h5><%= form.text_field :name,:required=>true, class:"label" %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :unique_id , label: "Employee ID",:required=>true , class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :gender, Pstaff::GENDER %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :mobile_no,label:"Mobile No",:required=>true, class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :department, Pstaff::TEMP ,:required=>true , class:"label" %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :applicant_type %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :address, :required=>true,class:"label"%></h5>
  </div>
  <div class="file">
    <h5><%= form.file_field :photo ,:required=>true , class:"label,ui pink button"%></h5>
  </div>
 

  <div class="file">
    <h5><%= form.file_field :id_proof ,:required=>true , class:"label,ui pink button"%></h5>
  </div>


  <div class="actions">
    <h5><%= form.submit "submit",class:"btn btn-primary" %></h5>
  </div>

</div>
</div>
</div>
</div>
<% end %>

app/views/user_profiles/_temporary_form.html.erb
<%= bootstrap_form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
        <% user_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container_fluid">
      <div class="row" >
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          <div class="shadow-lg p-3 mb-5 bg-black rounded">
            <div class="card ">
              <div class="card-header bg-info text-white text-center"><h2>Permanent Staff</h2></div>
              <div class="card-body"> <div class="field" >
  <div class="field">
   
    <h5><%= form.text_field :name,:required=>true, class:"label" %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :unique_id , label: "Employee ID",:required=>true , class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :gender, Pstaff::GENDER %></h5>
  </div>

  <div class="field">
    
    <h5><%= form.text_field :mobile_no,label:"Mobile No",:required=>true, class:"label" %></h5>
  </div>

  <div class="dropdown">
   
    <h5><%= form.select :department, Pstaff::TEMP ,:required=>true , class:"label" %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :applicant_type %></h5>
  </div>

  <div class="field">
   
    <h5><%= form.text_field :address, :required=>true,class:"label"%></h5>
  </div>
  <div class="file">
    <h5><%= form.file_field :photo ,:required=>true , class:"label,ui pink button"%></h5>
  </div>
 

  <div class="file">
    <h5><%= form.file_field :id_proof ,:required=>true , class:"label,ui pink button"%></h5>
  </div>


  <div class="actions">
    <h5><%= form.submit "submit",class:"btn btn-primary" %></h5>
  </div>

</div>
</div>
</div>
</div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing User Profile</h1>
<%if @user_profile.applicant_type == "Parmanent Staff" %>
  <%= render 'form', user_profile: @user_profile %>

<% elsif  @user_profile.applicant_type == "Temporaty Staff"%>
  <%= render 'temporary_form', user_profile: @user_profile %>
  <%elsif @user_profile.applicant_type == "STudent" %>
  <%= render 'scholars_form', user_profile: @user_profile %>
  <%else %>
  <%= render 'others_form', user_profile: @user_profile %>
  <%end %>



<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<div class="d-flex" id="wrapper">
  
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"><b><%= user_profile.name %></b></div>
      <div class="list-group list-group-flush">
        <a href="#" class="list-group-item list-group-item-action bg-light"><%= user_profile.department %></a>
        <a href="#" class="list-group-item list-group-item-action bg-light"><%= user_profile.mobile_no %></a>
       
      </div>
    </div>
  
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        
      </nav>

        <table id="example" class="table table-striped table-bordered nowrap" style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Unique</th>
      <th>Gender</th>
      <th>Mobile no</th>
      <th>Department</th>
      <th>Applicant type</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <!-- <td><%= user_profile.name %></td>
        <td><%= user_profile.unique_id %></td>
        <td><%= user_profile.gender %></td>
        <td><%= user_profile.mobile_no %></td>
        <td><%= user_profile.department %></td>
        <td><%= user_profile.applicant_type %></td>
        <td><%= user_profile.address %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>

  </tbody>
</table>

<br>
      
      <%= link_to 'New User Profile', new_user_profile_path %>
    </div>

<script >
$(document).ready(function() {
    var table = $('#example').DataTable( {
        responsive: true
    } );
 
    new $.fn.dataTable.FixedHeader( table );
} );
</script>

<script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

<style type="text/css">


#sidebar-wrapper {
  min-height: 100vh;
  margin-left: -15rem;
  -webkit-transition: margin .25s ease-out;
  -moz-transition: margin .25s ease-out;
  -o-transition: margin .25s ease-out;
  transition: margin .25s ease-out;
}

#sidebar-wrapper .sidebar-heading {
  padding: 0.875rem 1.25rem;
  font-size: 1.2rem;
}

#sidebar-wrapper .list-group {
  width: 15rem;
}

#page-content-wrapper {
  min-width: 100vw;
}

#wrapper.toggled #sidebar-wrapper {
  margin-left: 0;
}

@media (min-width: 768px) {
  #sidebar-wrapper {
    margin-left: 0;
  }

  #page-content-wrapper {
    min-width: 0;
    width: 100%;
  }

  #wrapper.toggled #sidebar-wrapper {
    margin-left: -15rem;
  }
}
</style>
<script type="text/javascript">
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

app/views/user_profiles/new.html.erb
<h1>New User Profile</h1>
<% @user_profile.applicant_type = 'Parmanent Staff' %>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/others.html.erb
<h1>New User Profile</h1>
<% @user_profile.applicant_type = 'Others' %>
<%= render 'others_form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/scholars.html.erb
<h1>New User Profile</h1>
<% @user_profile.applicant_type = 'Student' %>
<%= render 'scholars_form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_profile.name %>
</p>

<p>
  <strong>Unique:</strong>
  <%= @user_profile.unique_id %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user_profile.gender %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @user_profile.mobile_no %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user_profile.department %>
</p>

<p>
  <strong>Applicant type:</strong>
  <%= @user_profile.applicant_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user_profile.address %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/temporary_staff.html.erb
<h1>New User Profile</h1>
<% @user_profile.applicant_type = 'Temporary Staff' %>

<%= render 'temporary_form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>