config/routes.rb
Rails.application.routes.draw do


  #resources :phases

  root "home#home1"
  get "phases/phase1"
  get "phases/phase2"
  get "phases/phase3"
  get 'home/about'
  get 'home/contact'
  get 'pstaffs/showuser'
  get 'home/index'


  get 'user_profiles/temporary_staff'
  get 'user_profiles/scholars'
  get 'user_profiles/others'

  get "check/phase1/pstaff/:id", :action=>"show_form",:controller =>"check", :as =>"show_user_form"
  patch "/generate/sticker/:id", :action=>"sticker",:controller =>"check",:as =>"sticker_number"
  patch "/generate/remark/:id", :action=>"remark",:controller=>"check", :as =>"remark"



  resources :pstaffs
  resources :user_profiles

  devise_scope :user do
  	delete 'sign_out', to: 'devise/sessions#new'
  end

  devise_for :users, controllers: { registrations: "registrations" }


  resources :users


  get "check/phase1"
  get "check/phase2"
  get "check/phase3"
  #get "check/sticker"
  get  "check/show_user_form/:id" , :action=>"show_user_form", :controller=>"check", :as=>"show_user"
  post "request/approve/:id" , :action=>"approve",:controller=>"check",:as=>"approve"  
  post "request/disapprove/:id" , :action=>"disapprove",:controller=>"check",:as=>"disapprove"  

  post'request/check/:id' => 'check#create', :action=> "create", :controller=>"check" ,:as => 'check'


  get :approve_mail, to: 'notification#approve_mail', as: :approve_mail
  get :recive_mail, to: 'notify#recive_mail', as: :recive_mail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
 <header>
  
  <div class="container h-100 ">
    <div class="d-flex text-center h-100">
      <div class="my-auto w-100 text-white">
        <h1 class="display-4" id="nitkfont">National Institute of Technology, Karnataka</h1>
        <h2 id="nitkfont1"> Security Stickers</h2>
      </div>
    </div>
  </div>
</header>

 <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav mr-auto">
        
  <% if current_user %>
   <% if current_user.phase1 == true %>
   <li class="nav-item active">

      <a ><b><%= link_to "Home",check_phase1_path,class:"nav-link", style:"font-size:22px;color: white";%></b></a>
   </li>
   <a ><b><%=  link_to "About",home_about_path ,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>
      </li>
      <li class="nav-item">
      <a ><b><%= link_to "Contact us",home_contact_path,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>


   <% elsif current_user.phase2 == true %>
   <li>
   <a ><b><%= link_to "Home",check_phase2_path, class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a></li>
   <a ><b><%=  link_to "About",home_about_path ,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>
      </li>
      <li class="nav-item">
      <a ><b><%= link_to "Contact us",home_contact_path,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>


   <% elsif current_user.phase3 == true %>
   <li><a ><b><%= link_to "Home",check_phase3_path, class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a></li>
   <a ><b><%=  link_to "About",home_about_path ,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>
      </li>
      <li class="nav-item">
      <a ><b><%= link_to "Contact us",home_contact_path,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>

   <% else %>
    <% @user_profile = current_user.user_profiles %>
      <% if @user_profile.ids.count == 0 %>
      <li><a ><b><%= link_to "Home",home_index_path, class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a></li>
      <a ><b><%=  link_to "About",home_about_path ,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>
      </li>
      <li class="nav-item">
      <a ><b><%= link_to "Contact us",home_contact_path,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>

      <% else  %>
  <li> <a ><b><%= link_to "Home",pstaffs_path, class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a></li>
  <a ><b><%=  link_to "About",home_about_path ,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>
      </li>
      <li class="nav-item">
      <a ><b><%= link_to "Contact us",home_contact_path,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>


     <% end %>
     <% end %>
   
   
  </div>    
  
  <% else %>

   <li><a ><b><%= link_to "Home",root_path, class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a></li>
   <li>
    <a ><b><%=  link_to "About",home_about_path ,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>
      </li>
      <li class="nav-item">
      <a ><b><%= link_to "Contact us",home_contact_path,class:"navbar-brand text-left",style:"font-size:22px;color: white;" %></b></a>

  <%end %>
  </ul>
  </div>
   <% if current_user %>
      <div class="mx-auto order-0">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <li><a ><%= link_to "signout" , destroy_user_session_path ,method:  :delete,class:"btn btn-success ml-auto mr-1 btn-md" %></a></li>
  <li> <a> <%= link_to 'change password' , edit_user_registration_path,class:"btn btn-success ml-auto mr-1 btn-md"  %></a></li>
  </li>
  </ul>
  </div>
  
<% else %>
  <div class="mx-auto order-0">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <li> <a ><%= link_to "Sign up",new_user_registration_path, class:"btn btn-success ml-auto mr-1 btn-md" %></a></li>
      <li><a ><%= link_to "Sign in",new_user_session_path, class:"btn btn-success ml-auto mr-1 btn-md" %></a></li>
    </li>
    </ul>
  </div>
  <%end%>
</nav>




<style>
  header {
  position: relative;
  background-color: black;
  height: 18vh;
  /*min-height: 20rem;*/
  width: 100%;
  overflow: hidden;
}


header .container {
  position: relative;
  z-index: 2;
}

@media only screen and (max-width: 1200px) {
  #nitkfont {
   font-size: 3em;
  }
  #nitkfont1 {
   font-size: 3em;
  }
}
@media only screen and (max-width: 700px) {
  #nitkfont {
   font-size: 1.8em;
  }
  #nitkfont1 {
   font-size: 1.8em;
  }
}
/*@media only screen and (max-width: 600px) {
  #nitkfont {
   font-size: 4em;
  }
}
@media only screen and (max-width: 300px) {
  #nitkfont {
   font-size: 6em;
  }
}*/

}

</style>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head >
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>





    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <meta name="turbolinks-cache-control" content="no-cache">

  <%= stylesheet_link_tag "application.css" %>
  </head>
  <body style="margin:0px;">
<%= render 'layouts/menu' %>
  <div class="container">
  <%= render 'layouts/messages' %>
  </div>
    <%#= render 'layouts/messages' %>
<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->


  
  <%= yield  %>

  </body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<!-- <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script> -->
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>

<script >$(document).ready( function () {
    $('#phase1_id').DataTable();
} )</script>